; pokemon ids
; indexes for:
; - PokemonNames (see data/pokemon/names.asm)
; - BaseData (see data/pokemon/base_stats.asm)
; - EvosAttacksPointers (see data/pokemon/evos_attacks_pointers.asm)
; - EggMovePointers (see data/pokemon/egg_move_pointers.asm)
; - PokemonCries (see data/pokemon/cries.asm)
; - MonMenuIcons (see data/pokemon/menu_icons.asm)
; - PokemonPicPointers (see data/pokemon/pic_pointers.asm)
; - PokemonPalettes (see data/pokemon/palettes.asm)
; - PokedexDataPointerTable (see data/pokemon/dex_entry_pointers.asm)
; - AlphabeticalPokedexOrder (see data/pokemon/dex_order_alpha.asm)
; - EZChat_SortedPokemon (see data/pokemon/ezchat_order.asm)
; - NewPokedexOrder (see data/pokemon/dex_order_new.asm)
; - Pokered_MonIndices (see data/pokemon/gen1_order.asm)
; - AnimationPointers (see gfx/pokemon/anim_pointers.asm)
; - AnimationIdlePointers (see gfx/pokemon/idle_pointers.asm)
; - BitmasksPointers (see gfx/pokemon/bitmask_pointers.asm)
; - FramesPointers (see gfx/pokemon/frame_pointers.asm)
; - Footprints (see gfx/footprints.asm)
	const_def 1
	const BULBASAUR  ; 001
	const IVYSAUR    ; 002
	const VENUSAUR   ; 003
	const CHARMANDER ; 004
	const CHARMELEON ; 005
	const CHARIZARD  ; 006
	const SQUIRTLE   ; 007
	const WARTORTLE  ; 008
	const BLASTOISE  ; 009
	const CATERPIE   ; 00a
	const METAPOD    ; 00b
	const BUTTERFREE ; 00c
	const WEEDLE     ; 00d
	const KAKUNA     ; 00e
	const BEEDRILL   ; 00f
	const PIDGEY     ; 010
	const PIDGEOTTO  ; 011
	const PIDGEOT    ; 012
	const RATTATA    ; 013
	const RATICATE   ; 014
	const SPEAROW    ; 015
	const FEAROW     ; 016
	const EKANS      ; 017
	const ARBOK      ; 018
	const PIKACHU    ; 019
	const RAICHU     ; 01a
	const SANDSHREW  ; 01b
	const SANDSLASH  ; 01c
	const NIDORAN_F  ; 01d
	const NIDORINA   ; 01e
	const NIDOQUEEN  ; 01f
	const NIDORAN_M  ; 020
	const NIDORINO   ; 021
	const NIDOKING   ; 022
	const CLEFAIRY   ; 023
	const CLEFABLE   ; 024
	const VULPIX     ; 025
	const NINETALES  ; 026
	const JIGGLYPUFF ; 027
	const WIGGLYTUFF ; 028
	const ZUBAT      ; 029
	const GOLBAT     ; 02a
	const ODDISH     ; 02b
	const GLOOM      ; 02c
	const VILEPLUME  ; 02d
	const PARAS      ; 02e
	const PARASECT   ; 02f
	const VENONAT    ; 030
	const VENOMOTH   ; 031
	const DIGLETT    ; 032
	const DUGTRIO    ; 033
	const MEOWTH     ; 034
	const PERSIAN    ; 035
	const PSYDUCK    ; 036
	const GOLDUCK    ; 037
	const MANKEY     ; 038
	const PRIMEAPE   ; 039
	const GROWLITHE  ; 03a
	const ARCANINE   ; 03b
	const POLIWAG    ; 03c
	const POLIWHIRL  ; 03d
	const POLIWRATH  ; 03e
	const ABRA       ; 03f
	const KADABRA    ; 040
	const ALAKAZAM   ; 041
	const MACHOP     ; 042
	const MACHOKE    ; 043
	const MACHAMP    ; 044
	const BELLSPROUT ; 045
	const WEEPINBELL ; 046
	const VICTREEBEL ; 047
	const TENTACOOL  ; 048
	const TENTACRUEL ; 049
	const GEODUDE    ; 04a
	const GRAVELER   ; 04b
	const GOLEM      ; 04c
	const PONYTA     ; 04d
	const RAPIDASH   ; 04e
	const SLOWPOKE   ; 04f
	const SLOWBRO    ; 050
	const MAGNEMITE  ; 051
	const MAGNETON   ; 052
	const FARFETCH_D ; 053
	const DODUO      ; 054
	const DODRIO     ; 055
	const SEEL       ; 056
	const DEWGONG    ; 057
	const GRIMER     ; 058
	const MUK        ; 059
	const SHELLDER   ; 05a
	const CLOYSTER   ; 05b
	const GASTLY     ; 05c
	const HAUNTER    ; 05d
	const GENGAR     ; 05e
	const ONIX       ; 05f
	const DROWZEE    ; 060
	const HYPNO      ; 061
	const KRABBY     ; 062
	const KINGLER    ; 063
	const VOLTORB    ; 064
	const ELECTRODE  ; 065
	const EXEGGCUTE  ; 066
	const EXEGGUTOR  ; 067
	const CUBONE     ; 068
	const MAROWAK    ; 069
	const HITMONLEE  ; 06a
	const HITMONCHAN ; 06b
	const LICKITUNG  ; 06c
	const KOFFING    ; 06d
	const WEEZING    ; 06e
	const RHYHORN    ; 06f
	const RHYDON     ; 070
	const CHANSEY    ; 071
	const TANGELA    ; 072
	const KANGASKHAN ; 073
	const HORSEA     ; 074
	const SEADRA     ; 075
	const GOLDEEN    ; 076
	const SEAKING    ; 077
	const STARYU     ; 078
	const STARMIE    ; 079
	const MR__MIME   ; 07a
	const SCYTHER    ; 07b
	const JYNX       ; 07c
	const ELECTABUZZ ; 07d
	const MAGMAR     ; 07e
	const PINSIR     ; 07f
	const TAUROS     ; 080
	const MAGIKARP   ; 081
	const GYARADOS   ; 082
	const LAPRAS     ; 083
	const DITTO      ; 084
	const EEVEE      ; 085
	const VAPOREON   ; 086
	const JOLTEON    ; 087
	const FLAREON    ; 088
	const PORYGON    ; 089
	const OMANYTE    ; 08a
	const OMASTAR    ; 08b
	const KABUTO     ; 08c
	const KABUTOPS   ; 08d
	const AERODACTYL ; 08e
	const SNORLAX    ; 08f
	const ARTICUNO   ; 090
	const ZAPDOS     ; 091
	const MOLTRES    ; 092
	const DRATINI    ; 093
	const DRAGONAIR  ; 094
	const DRAGONITE  ; 095
	const MEWTWO     ; 096
	const MEW        ; 097
JOHTO_POKEMON EQU const_value
	const CHIKORITA  ; 098
	const BAYLEEF    ; 099
	const MEGANIUM   ; 09a
	const CYNDAQUIL  ; 09b
	const QUILAVA    ; 09c
	const TYPHLOSION ; 09d
	const TOTODILE   ; 09e
	const CROCONAW   ; 09f
	const FERALIGATR ; 0a0
	const SENTRET    ; 0a1
	const FURRET     ; 0a2
	const HOOTHOOT   ; 0a3
	const NOCTOWL    ; 0a4
	const LEDYBA     ; 0a5
	const LEDIAN     ; 0a6
	const SPINARAK   ; 0a7
	const ARIADOS    ; 0a8
	const CROBAT     ; 0a9
	const CHINCHOU   ; 0aa
	const LANTURN    ; 0ab
	const PICHU      ; 0ac
	const CLEFFA     ; 0ad
	const IGGLYBUFF  ; 0ae
	const TOGEPI     ; 0af
	const TOGETIC    ; 0b0
	const NATU       ; 0b1
	const XATU       ; 0b2
	const MAREEP     ; 0b3
	const FLAAFFY    ; 0b4
	const AMPHAROS   ; 0b5
	const BELLOSSOM  ; 0b6
	const MARILL     ; 0b7
	const AZUMARILL  ; 0b8
	const SUDOWOODO  ; 0b9
	const POLITOED   ; 0ba
	const HOPPIP     ; 0bb
	const SKIPLOOM   ; 0bc
	const JUMPLUFF   ; 0bd
	const AIPOM      ; 0be
	const SUNKERN    ; 0bf
	const SUNFLORA   ; 0c0
	const YANMA      ; 0c1
	const WOOPER     ; 0c2
	const QUAGSIRE   ; 0c3
	const ESPEON     ; 0c4
	const UMBREON    ; 0c5
	const MURKROW    ; 0c6
	const SLOWKING   ; 0c7
	const MISDREAVUS ; 0c8
	const UNOWN      ; 0c9
	const WOBBUFFET  ; 0ca
	const GIRAFARIG  ; 0cb
	const PINECO     ; 0cc
	const FORRETRESS ; 0cd
	const DUNSPARCE  ; 0ce
	const GLIGAR     ; 0cf
	const STEELIX    ; 0d0
	const SNUBBULL   ; 0d1
	const GRANBULL   ; 0d2
	const QWILFISH   ; 0d3
	const SCIZOR     ; 0d4
	const SHUCKLE    ; 0d5
	const HERACROSS  ; 0d6
	const SNEASEL    ; 0d7
	const TEDDIURSA  ; 0d8
	const URSARING   ; 0d9
	const SLUGMA     ; 0da
	const MAGCARGO   ; 0db
	const SWINUB     ; 0dc
	const PILOSWINE  ; 0dd
	const CORSOLA    ; 0de
	const REMORAID   ; 0df
	const OCTILLERY  ; 0e0
	const DELIBIRD   ; 0e1
	const MANTINE    ; 0e2
	const SKARMORY   ; 0e3
	const HOUNDOUR   ; 0e4
	const HOUNDOOM   ; 0e5
	const KINGDRA    ; 0e6
	const PHANPY     ; 0e7
	const DONPHAN    ; 0e8
	const PORYGON2   ; 0e9
	const STANTLER   ; 0ea
	const SMEARGLE   ; 0eb
	const TYROGUE    ; 0ec
	const HITMONTOP  ; 0ed
	const SMOOCHUM   ; 0ee
	const ELEKID     ; 0ef
	const MAGBY      ; 0f0
	const MILTANK    ; 0f1
	const BLISSEY    ; 0f2
	const RAIKOU     ; 0f3
	const ENTEI      ; 0f4
	const SUICUNE    ; 0f5
	const LARVITAR   ; 0f6
	const PUPITAR    ; 0f7
	const TYRANITAR  ; 0f8
	const LUGIA      ; 0f9
	const HO_OH      ; 0fa
	const CELEBI     ; 0fb
HOENN_POKEMON EQU const_value
	const TREECKO    ; 12d
	const GROVYLE    ; 12e
	const SCEPTILE   ; 12f
	const TORCHIC    ; 130
	const COMBUSKEN  ; 131
	const BLAZIKEN   ; 132
	const MUDKIP     ; 133
	const MARSHTOMP  ; 134
	const SWAMPERT   ; 135
	const POOCHYENA  ; 136
	const MIGHTYENA  ; 137
	const ZIGZAGOON  ; 138
	const LINOONE    ; 139
	const WURMPLE    ; 13a
	const SILCOON    ; 13b
	const BEAUTIFLY  ; 13c
	const CASCOON    ; 13d
	const DUSTOX     ; 13e
	const LOTAD      ; 13f
	const LOMBRE     ; 140
	const LUDICOLO   ; 141
	const SEEDOT     ; 142
	const NUZLEAF    ; 143
	const SHIFTRY    ; 144
	const TAILLOW    ; 145
	const SWELLOW    ; 146
	const WINGULL    ; 147
	const PELIPPER   ; 148
	const RALTS      ; 149
	const KIRLIA     ; 14a
	const GARDEVOIR  ; 14b
	const SURSKIT    ; 14c
	const MASQUERAIN ; 14d
	const SHROOMISH  ; 14e
	const BRELOOM    ; 14f
	const SLAKOTH    ; 150
	const VIGOROTH   ; 151
	const SLAKING    ; 152
	const NINCADA    ; 153
	const NINJASK    ; 154
	const SHEDINJA   ; 155
	const WHISMUR    ; 156
	const LOUDRED    ; 157
	const EXPLOUD    ; 158
	const MAKUHITA   ; 159
	const HARIYAMA   ; 15a
	const AZURILL    ; 15b
	const NOSEPASS   ; 15c
	const SKITTY     ; 15d
	const DELCATTY   ; 15e
	const SABLEYE    ; 15f
	const MAWILE     ; 160
	const ARON       ; 161
	const LAIRON     ; 162
	const AGGRON     ; 163
	const MEDITITE   ; 164
	const MEDICHAM   ; 165
	const ELECTRIKE  ; 166
	const MANECTRIC  ; 167
	const PLUSLE     ; 168
	const MINUN      ; 169
	const VOLBEAT    ; 16a
	const ILLUMISE   ; 16b
	const ROSELIA    ; 16c
	const GULPIN     ; 16d
	const SWALOT     ; 16e
	const CARVANHA   ; 16f
	const SHARPEDO   ; 170
	const WAILMER    ; 171
	const WAILORD    ; 172
	const NUMEL      ; 173
	const CAMERUPT   ; 174
	const TORKOAL    ; 175
	const SPOINK     ; 176
	const GRUMPIG    ; 177
	const SPINDA     ; 178
	const TRAPINCH   ; 179
	const VIBRAVA    ; 17a
	const FLYGON     ; 17b
	const CACNEA     ; 17c
	const CACTURNE   ; 17d
	const SWABLU     ; 17e
	const ALTARIA    ; 17f
	const ZANGOOSE   ; 180
	const SEVIPER    ; 181
	const LUNATONE   ; 182
	const SOLROCK    ; 183
	const BARBOACH   ; 184
	const WHISCASH   ; 185
	const CORPHISH   ; 186
	const CRAWDAUNT  ; 187
	const BALTOY     ; 188
	const CLAYDOL    ; 189
	const LILEEP     ; 18a
	const CRADILY    ; 18b
	const ANORITH    ; 18c
	const ARMALDO    ; 18d
	const FEEBAS     ; 18e
	const MILOTIC    ; 18f
	const CASTFORM   ; 190
	const KECLEON    ; 191
	const SHUPPET    ; 192
	const BANETTE    ; 193
	const DUSKULL    ; 194
	const DUSCLOPS   ; 195
	const TROPIUS    ; 196
	const CHIMECHO   ; 197
	const ABSOL      ; 198
	const WYNAUT     ; 199
	const SNORUNT    ; 19a
	const GLALIE     ; 19b
	const SPHEAL     ; 19c
	const SEALEO     ; 19d
	const WALREIN    ; 19e
	const CLAMPERL   ; 19f
	const HUNTAIL    ; 1a0
	const GOREBYSS   ; 1a1
	const RELICANTH  ; 1a2
	const LUVDISC    ; 1a3
	const BAGON      ; 1a4
	const SHELGON    ; 1a5
	const SALAMENCE  ; 1a6
	const BELDUM     ; 1a7
	const METANG     ; 1a8
	const METAGROSS  ; 1a9
	const REGIROCK   ; 1aa
	const REGICE     ; 1ab
	const REGISTEEL  ; 1ac
	const LATIAS     ; 1ad
	const LATIOS     ; 1ae
	const KYOGRE     ; 1af
	const GROUDON    ; 1b0
	const RAYQUAZA   ; 1b1
	const JIRACHI    ; 1b2
	const DEOXYS     ; 1b3
SINNOH_POKEMON EQU const_value
	const TURTWIG    ; 1b4
	const GROTLE     ; 1b5
	const TORTERRA   ; 1b6
	const CHIMCHAR   ; 1b7
	const MONFERNO   ; 1b8
	const INFERNAPE  ; 1b9
	const PIPLUP     ; 1ba
	const PRINPLUP   ; 1bb
	const EMPOLEON   ; 1bc
	const STARLY     ; 1bd
	const STARAVIA   ; 1be
	const STARAPTOR  ; 1bf
	const BIDOOF     ; 1c0
	const BIBAREL    ; 1c1
	const KRICKETOT  ; 1c2
	const KRICKETUNE ; 1c3
	const SHINX      ; 1c4
	const LUXIO      ; 1c5
	const LUXRAY     ; 1c6
	const BUDEW      ; 1c7
	const ROSERADE   ; 1c8
	const CRANIDOS   ; 1c9
	const RAMPARDOS  ; 1ca
	const SHIELDON   ; 1cb
	const BASTIODON  ; 1cc
	const BURMY      ; 1cd
	const WORMADAM   ; 1ce
	const MOTHIM     ; 1cf
	const COMBEE     ; 1d0
	const VESPIQUEN  ; 1d1
	const PACHIRISU  ; 1d2
	const BUIZEL     ; 1d3
	const FLOATZEL   ; 1d4
	const CHERUBI    ; 1d5
	const CHERRIM    ; 1d6
	const SHELLOS    ; 1d7
	const GASTRODON  ; 1d8
	const AMBIPOM    ; 1d9
	const DRIFLOON   ; 1da
	const DRIFBLIM   ; 1db
	const BUNEARY    ; 1dc
	const LOPUNNY    ; 1dd
	const MISMAGIUS  ; 1de
	const HONCHKROW  ; 1df
	const GLAMEOW    ; 1e0
	const PURUGLY    ; 1e1
	const CHINGLING  ; 1e2
	const STUNKY     ; 1e3
	const SKUNTANK   ; 1e4
	const BRONZOR    ; 1e5
	const BRONZONG   ; 1e6
	const BONSLY     ; 1e7
	const MIME_JR    ; 1e8
	const HAPPINY    ; 1e9
	const CHATOT     ; 1ea
	const SPIRITOMB  ; 1eb
	const GIBLE      ; 1ec
	const GABITE     ; 1ed
	const GARCHOMP   ; 1ee
	const MUNCHLAX   ; 1ef
	const RIOLU      ; 1f0
	const LUCARIO    ; 1f1
	const HIPPOPOTAS ; 1f2
	const HIPPOWDON  ; 1f3
	const SKORUPI    ; 1f4
	const DRAPION    ; 1f5
	const CROAGUNK   ; 1f6
	const TOXICROAK  ; 1f7
	const CARNIVINE  ; 1f8
	const FINNEON    ; 1f9
	const LUMINEON   ; 1fa
	const MANTYKE    ; 1fb
	const SNOVER     ; 1fc
	const ABOMASNOW  ; 1fd
	const WEAVILE    ; 1fe
	const MAGNEZONE  ; 1ff
	const LICKILICKY ; 200
	const RHYPERIOR  ; 201
	const TANGROWTH  ; 202
	const ELECTIVIRE ; 203
	const MAGMORTAR  ; 204
	const TOGEKISS   ; 205
	const YANMEGA    ; 206
	const LEAFEON    ; 207
	const GLACEON    ; 208
	const GLISCOR    ; 209
	const MAMOSWINE  ; 20a
	const PORYGON_Z  ; 20b
	const GALLADE    ; 20c
	const PROBOPASS  ; 20d
	const DUSKNOIR   ; 20e
	const FROSLASS   ; 20f
	const ROTOM      ; 210
	const UXIE       ; 211
	const MESPRIT    ; 212
	const AZELF      ; 213
	const DIALGA     ; 214
	const PALKIA     ; 215
	const HEATRAN    ; 216
	const REGIGIGAS  ; 217
	const GIRATINA   ; 218
	const CRESSELIA  ; 219
	const PHIONE     ; 21a
	const MANAPHY    ; 21b
	const DARKRAI    ; 21c
	const SHAYMIN    ; 21d
	const ARCEUS     ; 21e
NIHON_POKEMON EQU const_value
	const FLAMBEAR   ; 0fc
	const VOLBEAR    ; 0fd
	const DYNABEAR   ; 0fe
	const CRUIZE     ; 0ff
	const AQUALLO    ; 100
	const AQUARIUS   ; 101
	const KOTORA     ; 102
	const RAITORA    ; 103
	const BOMSHEAL   ; 104
	const CORASUN    ; 105
	const CORAMOLA   ; 106
	const MAMBOKING  ; 107
	const BITEEL     ; 108
	const GROTESS    ; 109
	const RINRING    ; 10a
	const BELLRUN    ; 10b
	const BLOTTLE    ; 10c
	const PENDRAKEN  ; 10d
	const KURSTRAW   ; 10e
	const PANGSHI    ; 10f
	const WOLFAN     ; 110
	const WARWOLF    ; 111
	const CHEEP      ; 112
	const JABETTA    ; 113
	const SNOBIT     ; 114
	const BLIZBIT    ; 115
	const GLACIHARE  ; 116
	const STEMINEEL  ; 117
	const ARSKEED    ; 118
	const DRAKARVE   ; 119
	const PETICORN   ; 11a
	const GUPGOLD    ; 11b
	const TRITALES   ; 11c
	const GRIMBY     ; 11d
	const PARAMITE   ; 11e
	const NYANYA     ; 11f
	const PUDDIPUP   ; 120
	const CHIX       ; 121
	const KATU       ; 122
	const TANGTRIP   ; 123
	const GELANIA    ; 124
	const BELMITT    ; 125
	const TURBAN     ; 126
	const PRAXE      ; 127
	const NUMBPUFF   ; 128
	const METTO      ; 129
	const MADAME     ; 12a
	const GUARDIA    ; 12b
	const OHMEGA     ; 12c
ALT_FORMS EQU const_value
	const PICHU_B     ; 21f
	const DEOXYS_A    ; 220
	const DEOXYS_D    ; 221
	const DEOXYS_S    ; 222
	const BURMY_S     ; 223
	const BURMY_T     ; 224
	const WORMADAM_S  ; 225
	const WORMADAM_T  ; 226
	const SHELLOS_E   ; 227
	const GASTRODON_E ; 228
	const ROTOM_FLY   ; 229
	const ROTOM_FRE   ; 22a
	const ROTOM_GRS   ; 22b
	const ROTOM_ICE   ; 22c
	const ROTOM_WTR   ; 22d
	const GIRATINA_O  ; 22e
	const SHAYMIN_S   ; 22f

NUM_POKEMON EQU const_value + -1

EGG EQU -3

; limits:
; 999: everything that prints dex counts
; 1407: size of wPokedexOrder
; 4095: hard limit; would require serious redesign to increase
if NUM_POKEMON > 999
	fail "Too many Pokémon defined!"
endc

; Unown forms
; indexes for:
; - UnownWords (see data/pokemon/unown_words.asm)
; - UnownPicPointers (see data/pokemon/unown_pic_pointers.asm)
; - UnownAnimationPointers (see gfx/pokemon/unown_anim_pointers.asm)
; - UnownAnimationIdlePointers (see gfx/pokemon/unown_idle_pointers.asm)
; - UnownBitmasksPointers (see gfx/pokemon/unown_bitmask_pointers.asm)
; - UnownFramesPointers (see gfx/pokemon/unown_frame_pointers.asm)
	const_def 1
	const UNOWN_A ;  1
	const UNOWN_B ;  2
	const UNOWN_C ;  3
	const UNOWN_D ;  4
	const UNOWN_E ;  5
	const UNOWN_F ;  6
	const UNOWN_G ;  7
	const UNOWN_H ;  8
	const UNOWN_I ;  9
	const UNOWN_J ; 10
	const UNOWN_K ; 11
	const UNOWN_L ; 12
	const UNOWN_M ; 13
	const UNOWN_N ; 14
	const UNOWN_O ; 15
	const UNOWN_P ; 16
	const UNOWN_Q ; 17
	const UNOWN_R ; 18
	const UNOWN_S ; 19
	const UNOWN_T ; 20
	const UNOWN_U ; 21
	const UNOWN_V ; 22
	const UNOWN_W ; 23
	const UNOWN_X ; 24
	const UNOWN_Y ; 25
	const UNOWN_Z ; 26
	const UNOWN_EXCLAMATION ; 27
	const UNOWN_QUESTION ; 28
NUM_UNOWN EQU const_value + -1 ; 26
