Debug_MusicNames::
	db "None@@@@@@@@@@@@@@"
	db "Placeholder@@@@@@@"
	db "Crystal Opening@@@"
	db "Title@@@@@@@@@@@@@"
	db "Main Menu@@@@@@@@@"
	db "Special Program@@@"
	db "Twinleaf Town@@@@@"
	db "Enc. Rival@@@@@@@@"
	db "Route 201@@@@@@@@@"
	db "Professor Rowan@@@"
	db "Dawn's Theme@@@@@@@"
	db "Lucas's Theme@@@@@@"
	db "Rival Battle@@@@@@"
	db "Trainer Victory@@@"
	db "Wild Battle@@@@@@@"
	db "Wild Battle Night@"
	db "Wild Victory@@@@@@"
	db "Captured Pokemon@@"
	db "Sandgem Town@@@@@@"
	db "Show Me Around@@@@"
	db "Pokemon Center@@@@"
	db "Pokemon Healed@@@@"
	db "Poke Mart@@@@@@@@@"
	db "Evolution@@@@@@@@@"
	db "Enc. Youngster@@@@"
	db "Trainer Battle@@@@"
	db "Enc. Lass@@@@@@@@@"
	db "Jubilife City@@@@@"
	db "Looker's Theme@@@@@"
	db "Route 203@@@@@@@@@"
	db "Oreburgh Gate@@@@@"
	db "Oreburgh City@@@@@"
	db "Oreburgh Mine@@@@@"
	db "Enc. Hiker@@@@@@@@"
	db "Gym@@@@@@@@@@@@@@@"
	db "Leader Battle@@@@@"
	db "Leader Victory@@@@"
	db "Enc. Galactic@@@@@"
	db "Galactic Battle@@@"
	db "Route 206@@@@@@@@@"
	db "Enc. Beauty@@@@@@@"
	db "Enc. PokeManiac@@@"
	db "Enc. Sage@@@@@@@@@"
	db "Enc. Officer@@@@@@"
	db "Bicycle@@@@@@@@@@@"
	db "Surfing@@@@@@@@@@@"
	db "Champion Battle@@@"
	db "Hall of Fame@@@@@@"
	db "Credits@@@@@@@@@@@"
	db "Post Credits@@@@@@"
	db "Professor Oak@@@@@"
	db "Battle Tower@@@@@@"
	db "Battle Twr. Lobby@"
	db "Poke Flute Ch.@@@@"
	db "Mom@@@@@@@@@@@@@@@"
	db "Pokemon Lullaby@@@"
	db "Pokemon March@@@@@"
	db "Printer Error@@@@@"
	db "Mobile Center@@@@@"
	db "Mobile Adpt. Menu@"
	db "Mobile Adapter@@@@"
	db "Unown Radio@@@@@@@"
	
	;Don't forget to update line 240 of debug_menu.asm
	