	tilepal 0, GRAY, GRAY, WATER, GREEN, BROWN, BROWN, BROWN, BROWN
	tilepal 0, BROWN, BROWN, GRAY, GRAY, GRAY, GRAY, GREEN, GREEN
	tilepal 0, BROWN, BROWN, BROWN, RED, BROWN, BROWN, BROWN, BROWN
	tilepal 0, BROWN, BROWN, GRAY, GRAY, GRAY, GRAY, GREEN, GREEN
	tilepal 0, BROWN, BROWN, BROWN, RED, BROWN, BROWN, BROWN, BROWN
	tilepal 0, BROWN, BROWN, BROWN, BROWN, GRAY, GRAY, BROWN, BROWN
	tilepal 0, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, WATER, WATER
	tilepal 0, GRAY, GRAY, BROWN, BROWN, WATER, GRAY, BROWN, BROWN
	tilepal 0, GRAY, GRAY, GRAY, BROWN, BROWN, BROWN, WATER, WATER
	tilepal 0, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, BROWN, BROWN
	tilepal 0, GRAY, GRAY, GRAY, BROWN, BROWN, BROWN, GRAY, GRAY
	tilepal 0, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, BROWN, BROWN

rept 32
	db $ff
endr

	tilepal 1, BROWN, WATER, WATER, RED, RED, RED, RED, RED
	tilepal 1, WATER, WATER, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN
	tilepal 1, RED, GRAY, BROWN, RED, RED, RED, RED, RED
	tilepal 1, WATER, WATER, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN
