	tilepal 0, GRAY, GREEN, GREEN, RED, RED, BROWN, BROWN, GRAY
	tilepal 0, GREEN, GREEN, BROWN, BROWN, GREEN, BROWN, BROWN, BROWN
	tilepal 0, GREEN, GREEN, GREEN, GREEN, WATER, BROWN, BROWN, GRAY
	tilepal 0, GREEN, GREEN, GREEN, BROWN, BROWN, BROWN, BROWN, BROWN
	tilepal 0, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, BROWN, GRAY
	tilepal 0, GREEN, BROWN, GREEN, BROWN, YELLOW, BROWN, BROWN, BROWN
	tilepal 0, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, BROWN, GREEN
	tilepal 0, BROWN, GREEN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN
	tilepal 0, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, BROWN, BROWN
	tilepal 0, BROWN, BROWN, GREEN, BROWN, BROWN, BROWN, BROWN, BROWN
	tilepal 0, GREEN, BROWN, BROWN, GREEN, GREEN, GREEN, BROWN, BROWN
	tilepal 0, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN

rept 32
	db $ff
endr

	tilepal 1, GRAY, BROWN, BROWN, RED, GRAY, GREEN, BROWN, GRAY
	tilepal 1, GRAY, BROWN, BROWN, BROWN, GREEN, GREEN, GREEN, GREEN
	tilepal 1, BROWN, BROWN, BROWN, RED, WATER, BROWN, BROWN, BROWN
	tilepal 1, BROWN, BROWN, BROWN, BROWN, GREEN, GREEN, GREEN, GREEN
	tilepal 1, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, GREEN, GREEN
	tilepal 1, GREEN, BROWN, BROWN, BROWN, GREEN, GREEN, GREEN, GREEN
	tilepal 1, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, GREEN, GREEN
	tilepal 1, GREEN, GREEN, GREEN, GREEN, GREEN, BROWN, BROWN, GREEN
	tilepal 1, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN
	tilepal 1, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN
	tilepal 1, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN
	tilepal 1, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN
