	tilepal 0, GRAY, WATER, WATER, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 0, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 0, RED, RED, RED, BROWN, BROWN, BROWN, GRAY, GRAY
	tilepal 0, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 0, RED, RED, RED, PRIORITY_YELLOW, PRIORITY_YELLOW, GRAY, GRAY, GRAY
	tilepal 0, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	
rept 32
	db $ff
endr