	tilepal 0, GRAY, WATER, RED, RED, RED, WATER, RED, RED
	tilepal 0, GRAY, GREEN, GREEN, BROWN, BROWN, BROWN, BROWN, BROWN
	tilepal 0, WATER, WATER, WATER, WATER, WATER, WATER, RED, RED
	tilepal 0, GRAY, GREEN, GREEN, BROWN, BROWN, BROWN, BROWN, BROWN
	tilepal 0, WATER, WATER, WATER, WATER, WATER, WATER, BROWN, BROWN
	tilepal 0, GRAY, ROOF, ROOF, BROWN, WATER, BROWN, BROWN, BROWN
	tilepal 0, YELLOW, GREEN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN
	tilepal 0, GRAY, ROOF, ROOF, BROWN, BROWN, BROWN, BROWN, BROWN
	tilepal 0, GREEN, YELLOW, GREEN, GREEN, GREEN, GREEN, BROWN, BROWN
	tilepal 0, WATER, WATER, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 0, BROWN, BROWN, YELLOW, YELLOW, YELLOW, WATER, BROWN, BROWN
	tilepal 0, WATER, WATER, BROWN, BROWN, GRAY, GRAY, GRAY, GRAY

rept 32
	db $ff
endr

	tilepal 1, GRAY, GRAY, GRAY, GRAY, TEXT, TEXT, TEXT, TEXT
	tilepal 1, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT
	tilepal 1, GRAY, GRAY, GRAY, GRAY