	tilepal 0, GRAY, GREEN, GREEN, RED, GRAY, GRAY, GRAY, WATER
	tilepal 0, WATER, WATER, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF
	tilepal 0, ROOF, ROOF, ROOF, GRAY, BROWN, GRAY, GRAY, RED
	tilepal 0, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, GREEN, GREEN
	tilepal 0, BROWN, BROWN, BROWN, RED, RED, YELLOW, YELLOW, YELLOW
	tilepal 0, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, GREEN, GREEN
	tilepal 0, BROWN, BROWN, BROWN, BROWN, RED, RED, YELLOW, YELLOW
	tilepal 0, GRAY, YELLOW, YELLOW, BROWN, BROWN, BROWN, GREEN, GREEN
	tilepal 0, RED, BROWN, BROWN, BROWN, RED, RED, BROWN, BROWN
	tilepal 0, GRAY, BROWN, BROWN, BROWN, BROWN, BROWN, GREEN, GREEN
	tilepal 0, BROWN, BROWN, BROWN, BROWN, RED, RED, BROWN, BROWN
	tilepal 0, GRAY, GRAY, GRAY, BROWN, BROWN, BROWN, GREEN, GREEN

rept 32
	db $ff
endr

	tilepal 1, ROOF, ROOF, ROOF, ROOF, BROWN, BROWN, BROWN, RED
	tilepal 1, RED, RED, RED, RED, RED, ROOF, ROOF, ROOF
	tilepal 1, ROOF, RED, ROOF, ROOF, BROWN, GRAY, BROWN, BROWN
	tilepal 1, BROWN, BROWN, BROWN, GRAY, GRAY, ROOF, ROOF, ROOF
	tilepal 1, ROOF, ROOF, ROOF, ROOF, BROWN, BROWN, BROWN, BROWN
	tilepal 1, BROWN, GRAY, GRAY, GRAY, GRAY, ROOF, ROOF, ROOF
	tilepal 1, ROOF, ROOF, ROOF, YELLOW, ROOF, GRAY, GRAY, BROWN
	tilepal 1, BROWN, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, BROWN
	tilepal 1, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN
	tilepal 1, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN
	tilepal 1, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN
	tilepal 1, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN
