	tilepal 0, GRAY, GREEN, GREEN, RED, YELLOW, WATER, BROWN, BROWN
	tilepal 0, BROWN, BROWN, BROWN, GREEN, GREEN, RED, RED, RED
	tilepal 0, ROOF, GREEN, GREEN, GRAY, WATER, GREEN, BROWN, BROWN
	tilepal 0, BROWN, GREEN, BROWN, GREEN, GREEN, RED, RED, RED
	tilepal 0, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, BROWN, GRAY
	tilepal 0, BROWN, BROWN, BROWN, GREEN, GREEN, BROWN, BROWN, BROWN
	tilepal 0, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, BROWN, GRAY
	tilepal 0, BROWN, GRAY, BROWN, GREEN, GREEN, BROWN, BROWN, BROWN
	tilepal 0, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, BROWN, BROWN
	tilepal 0, BROWN, BROWN, GRAY, BROWN, BROWN, BROWN, BROWN, BROWN
	tilepal 0, GREEN, BROWN, BROWN, GREEN, GREEN, GREEN, BROWN, BROWN
	tilepal 0, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN

rept 32
	db $ff
endr

	tilepal 1, GRAY, BROWN, BROWN, RED, GRAY, GRAY, BROWN, GRAY
	tilepal 1, GRAY, BROWN, BROWN, BROWN, GRAY, GRAY, GRAY, GRAY
	tilepal 1, BROWN, BROWN, BROWN, RED, WATER, BROWN, BROWN, BROWN
	tilepal 1, BROWN, BROWN, BROWN, BROWN, GRAY, GRAY, GRAY, GRAY
	tilepal 1, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, GRAY, GRAY
	tilepal 1, GRAY, BROWN, BROWN, BROWN, GRAY, GRAY, GRAY, GRAY
	tilepal 1, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, GRAY, GRAY
	tilepal 1, GRAY, GRAY, GRAY, GRAY, GRAY, BROWN, BROWN, GRAY
	tilepal 1, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN
	tilepal 1, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN
	tilepal 1, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN
	tilepal 1, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN
