	tilepal 0, GRAY, RED, GRAY, ROOF, ROOF, ROOF, GRAY, GRAY
	tilepal 0, BROWN, BROWN, BROWN, GRAY, GRAY, GRAY, GREEN, GREEN
	tilepal 0, WATER, GRAY, GRAY, ROOF, ROOF, ROOF, BROWN, BROWN
	tilepal 0, BROWN, BROWN, BROWN, GRAY, GRAY, GRAY, GREEN, GREEN
	tilepal 0, YELLOW, YELLOW, ROOF, ROOF, ROOF, ROOF, GRAY, GRAY
	tilepal 0, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, BROWN, BROWN
	tilepal 0, YELLOW, YELLOW, BROWN, BROWN, RED, RED, GRAY, GRAY
	tilepal 0, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, BROWN, BROWN

rept 32
	db $ff
endr