	tilepal 0, GRAY, RED, BROWN, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 0, YELLOW, YELLOW, GRAY, GRAY, RED, RED, GREEN, GREEN
	tilepal 0, RED, WATER, BROWN, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 0, GRAY, GRAY, GRAY, GRAY, RED, RED, GREEN, GREEN
	tilepal 0, RED, WATER, BROWN, GRAY, BROWN, GRAY, GRAY, GRAY
	tilepal 0, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, YELLOW, YELLOW
	tilepal 0, BROWN, BROWN, BROWN, GRAY, GRAY, GRAY, GRAY, BROWN
	tilepal 0, GRAY, GRAY, WATER, WATER, RED, RED, GRAY, GRAY
	tilepal 0, BROWN, BROWN, BROWN, BROWN, YELLOW, YELLOW, GRAY, GRAY
	tilepal 0, GRAY, GRAY, WATER, WATER, GRAY, GRAY, GRAY, GRAY
	tilepal 0, BROWN, BROWN, BROWN, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 0, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY

rept 32
	db $ff
endr

	tilepal 1, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW
	tilepal 1, YELLOW, YELLOW, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 1, GRAY, GRAY, GRAY, GRAY, RED, YELLOW, YELLOW, RED
	tilepal 1, ROOF, RED, RED, ROOF, GRAY, GRAY, GRAY, GRAY
