	tilepal 0, GRAY, RED, BROWN, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 0, YELLOW, YELLOW, GRAY, GRAY, RED, RED, GREEN, GREEN
	tilepal 0, RED, WATER, BROWN, GRAY, WATER, GRAY, GRAY, GRAY
	tilepal 0, GRAY, GRAY, GRAY, GRAY, RED, RED, GREEN, GREEN
	tilepal 0, RED, WATER, BROWN, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 0, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, YELLOW, YELLOW
	tilepal 0, BROWN, BROWN, BROWN, ROOF, ROOF, RED, WATER, WATER
	tilepal 0, GRAY, GRAY, WATER, WATER, RED, RED, GRAY, GRAY
	tilepal 0, BROWN, BROWN, BROWN, ROOF, ROOF, RED, WATER, WATER
	tilepal 0, GRAY, GRAY, WATER, WATER, GRAY, GRAY, GRAY, GRAY
	tilepal 0, BROWN, BROWN, BROWN, ROOF, ROOF, GRAY, GRAY, GRAY
	tilepal 0, BROWN, BROWN, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY

rept 32
	db $ff
endr

	tilepal 1, BROWN, BROWN, GRAY, GRAY, GRAY, GRAY, BROWN, BROWN
	tilepal 1, GRAY, RED, BROWN, BROWN, GRAY, GRAY, RED, RED
	tilepal 1, BROWN, BROWN, GRAY, GRAY, GRAY, GRAY, BROWN, BROWN
	tilepal 1, GRAY, GRAY, BROWN, BROWN, GRAY, GRAY, RED, RED
