	tilepal 0, GRAY, GREEN, GRAY, RED, GRAY, GRAY, GRAY, BROWN
	tilepal 0, BROWN, BROWN, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF
	tilepal 0, ROOF, ROOF, ROOF, GREEN, WATER, GRAY, GRAY, BROWN
	tilepal 0, BROWN, BROWN, RED, BROWN, BROWN, BROWN, GREEN, GREEN
	tilepal 0, GRAY, GRAY, BROWN, BROWN, RED, BROWN, GREEN, BROWN
	tilepal 0, YELLOW, YELLOW, YELLOW, BROWN, BROWN, BROWN, GREEN, GREEN
	tilepal 0, GRAY, GRAY, GRAY, BROWN, RED, RED, BROWN, BROWN
	tilepal 0, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, GREEN, GREEN
	tilepal 0, GRAY, GRAY, YELLOW, BROWN, GRAY, BROWN, GRAY, GREEN
	tilepal 0, GREEN, RED, RED, BROWN, GRAY, GRAY, BROWN, BROWN
	tilepal 0, GRAY, GRAY, GRAY, BROWN, GRAY, GRAY, GRAY, GREEN
	tilepal 0, GREEN, RED, RED, BROWN, GRAY, GRAY, BROWN, BROWN

rept 32
	db $ff
endr

	tilepal 1, RED, RED, RED, BROWN, BROWN, BROWN, BROWN, BROWN
	tilepal 1, BROWN, BROWN, YELLOW, YELLOW, YELLOW, GRAY, BROWN, GRAY
	tilepal 1, RED, RED, RED, BROWN, BROWN, BROWN, BROWN, BROWN
	tilepal 1, BROWN, BROWN, GRAY, BROWN, BROWN, GRAY, BROWN, GRAY
	tilepal 1, RED, RED, RED, BROWN, BROWN, BROWN, ROOF, BROWN
	tilepal 1, ROOF, ROOF, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
