; See song sections in audio.asm.

Music:
; entries correspond to MUSIC_* constants
	dba Music_Nothing
	dba Music_Placeholder
	dba Music_CrystalOpening
	dba Music_TitleScreen
	dba Music_MainMenu
	dba Music_SpecialProgram
	dba Music_TwinleafTown
	dba Music_LookRival
	dba Music_Route201
	dba Music_RowansLab
	dba Music_DawnsTheme
	dba Music_LucassTheme
	dba Music_RivalBattle
	dba Music_TrainerVictory
	dba Music_SinnohWildBattle
	dba Music_SinnohWildBattleNight
	dba Music_WildPokemonVictory
	dba Music_SuccessfulCapture
	dba Music_CherrygroveCity
	dba Music_ShowMeAround
	dba Music_PokemonCenter
	dba Music_HealPokemon
	dba Music_PokeMart
	dba Music_Evolution
	dba Music_LookYoungster
	dba Music_SinnohTrainerBattle
	dba Music_LookLass
	dba Music_VioletCity
	dba Music_LookMysticalMan
	dba Music_Route203
	dba Music_OreburghGate
	dba Music_OreburghCity
	dba Music_UnionCave
	dba Music_LookHiker
	dba Music_Gym
	dba Music_SinnohGymBattle
	dba Music_GymLeaderVictory
	dba Music_LookRocket
	dba Music_RocketBattle
	dba Music_Route206
	dba Music_LookBeauty
	dba Music_LookPokemaniac
	dba Music_LookSage
	dba Music_LookOfficer
	dba Music_Bicycle
	dba Music_Surf
	dba Music_ChampionBattle
	dba Music_HallOfFame
	dba Music_Credits
	dba Music_PostCredits
	dba Music_ProfOak
	dba Music_BattleTowerTheme
	dba Music_BattleTowerLobby
	dba Music_PokeFluteChannel
	dba Music_Mom
	dba Music_PokemonLullaby
	dba Music_PokemonMarch
	dba Music_Printer
	dba Music_MobileCenter
	dba Music_MobileAdapterMenu
	dba Music_MobileAdapter
	dba Music_RuinsOfAlphRadio
	